spring.application.name=Real-Estate-Backend
server.port=8080

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/real_estate_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Entity Scanning
spring.jpa.packages-to-scan=com.icet.model.entity

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

APP_ADMIN_PASSWORD=admin123
APP_ADMIN_USERNAME=admin
APP_ADMIN_EMAIL=admin@realestate.com


